INFO b''
INFO b''
ERROR Internal Server Error: /user/verifycode/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 267, in verifycode
    rand_str += str1[random.randrange(0,255),random.randrange(0,len(str1))]
NameError: name 'str1' is not defined
ERROR Internal Server Error: /user/verifycode/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 267, in verifycode
    rand_str += str1[random.randrange(0,255),random.randrange(0,len(str1))]
NameError: name 'str1' is not defined
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/verifycode/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 267, in verifycode
    rand_str += str1[random.randrange(0,255),random.randrange(0,len(str1))]
NameError: name 'str1' is not defined
ERROR Internal Server Error: /user/verifycode/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 267, in verifycode
    rand_str += str1[random.randrange(0,255),random.randrange(0,len(str1))]
NameError: name 'str1' is not defined
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
INFO b''
INFO b''
ERROR Internal Server Error: /user/verifycode/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 267, in verifycode
    rand_str += str1[random.randrange(0,255),random.randrange(0,len(str1))]
NameError: name 'str1' is not defined
ERROR Internal Server Error: /user/verifycode/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 267, in verifycode
    rand_str += str1[random.randrange(0,255),random.randrange(0,len(str1))]
NameError: name 'str1' is not defined
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
INFO b''
INFO b''
INFO b''
INFO b''
WARNING Not Found: /favicon.ico
WARNING Not Found: /favicon.ico
ERROR Internal Server Error: /user/verifycode/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 267, in verifycode
    rand_str += str1[random.randrange(0,255),random.randrange(0,len(str1))]
NameError: name 'str1' is not defined
ERROR Internal Server Error: /user/verifycode/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 267, in verifycode
    rand_str += str1[random.randrange(0,255),random.randrange(0,len(str1))]
NameError: name 'str1' is not defined
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
WARNING Not Found: /user/login/user/verifycode/
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
ERROR Internal Server Error: /user/login_check/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 92, in login_check
    if verifycode.upper() != request.session['verifycode']:
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/contrib/sessions/backends/base.py", line 48, in __getitem__
    return self._session[key]
KeyError: 'verifycode'
INFO b''
INFO b''
INFO b''
INFO b''
ERROR Internal Server Error: /user/order/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/utils/decorators.py", line 9, in wrapper
    return view_func(request,*view_args,**view_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 243, in order
    return render(request,'users/user_center_order.html',context)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 1160, in load
    parser.add_library(lib)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 416, in add_library
    self.tags.update(lib.tags)
AttributeError: type object 'Library' has no attribute 'tags'
ERROR Internal Server Error: /user/order/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/utils/decorators.py", line 9, in wrapper
    return view_func(request,*view_args,**view_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 243, in order
    return render(request,'users/user_center_order.html',context)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 1160, in load
    parser.add_library(lib)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 416, in add_library
    self.tags.update(lib.tags)
AttributeError: type object 'Library' has no attribute 'tags'
INFO b''
INFO b''
WARNING Not Found: /search/
WARNING Not Found: /search/
WARNING Not Found: /search/
WARNING Not Found: /search/
WARNING Not Found: /search/
WARNING Not Found: /search/
ERROR Internal Server Error: /user/order/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/utils/decorators.py", line 9, in wrapper
    return view_func(request,*view_args,**view_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 243, in order
    return render(request,'users/user_center_order.html',context)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 1160, in load
    parser.add_library(lib)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 416, in add_library
    self.tags.update(lib.tags)
AttributeError: type object 'Library' has no attribute 'tags'
ERROR Internal Server Error: /user/order/
Traceback (most recent call last):
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atguigu/project/bookstore/utils/decorators.py", line 9, in wrapper
    return view_func(request,*view_args,**view_kwargs)
  File "/home/atguigu/project/bookstore/users/views.py", line 243, in order
    return render(request,'users/user_center_order.html',context)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/defaulttags.py", line 1160, in load
    parser.add_library(lib)
  File "/home/atguigu/Envs/python3/lib/python3.5/site-packages/django/template/base.py", line 416, in add_library
    self.tags.update(lib.tags)
AttributeError: type object 'Library' has no attribute 'tags'
WARNING Not Found: /search/
WARNING Not Found: /search/
INFO b''
INFO b''
WARNING Not Found: /search/
WARNING Not Found: /search/
